# Generated by Django 3.0.4 on 2020-03-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1', models.IntegerField()),
                ('v2', models.IntegerField()),
                ('v3', models.IntegerField()),
                ('v4', models.IntegerField()),
            ],
        ),
    ]
